export default interface ITutorialData {
  idproduct?: any | null,
  name: string,
  artist: string,
  year: string,
  datepost: any,
  datestart: any,
  dateend: any,
  numberallowed: any,
  venue: string,
  description: string,
  image: string,
  location_image: string,
  video: string,
  location_video: string,
  time: string,
  qrCodeImage: string,
  whoisposted: string
  // published?: boolean,
}